#! /bin/bash

# Enable the br_netfilter module for cluster communication
sudo modprobe br_netfilter
sudo echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
sudo echo '1' > /proc/sys/net/bridge/bridge-nf-call-ip6tables

sudo update-alternatives --set iptables /usr/sbin/iptables-legacy

# Control Plane Node(s)
sudo firewall-cmd --permanent --zone=public --add-port=6443/tcp # Kubernetes API server
sudo firewall-cmd --permanent --zone=public --add-port=2379-2380/tcp # etcd server client API
sudo firewall-cmd --permanent --zone=public --add-port=10250/tcp # Kubelet API
sudo firewall-cmd --permanent --zone=public --add-port=10251/tcp # kube-scheduler
sudo firewall-cmd --permanent --zone=public --add-port=10252/tcp # kube-controller-manager
sudo firewall-cmd --reload

# Worker Nodes
sudo firewall-cmd --permanent --zone=public --add-port=10250/tcp # Kubelet API
# sudo firewall-cmd --permanent --zone=public --add-port=30000-32767/tcp # NodePort Services**	
# sudo firewall-cmd --reload

# Add Kubernetes repo
sudo cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

# Configure cgroup driver used by kubelet on control-plane node
sudo sed -i '/^KUBELET_EXTRA_ARGS=/ s/$/--cgroup-driver=systemd/' /etc/sysconfig/kubelet

# Ensure iptables aren't being bypassed
sudo cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

sudo systemctl enable --now kubelet

sudo kubeadm init

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=scci-admin
kubectl create clusterrolebinding root-cluster-root-binding --clusterrole=cluster-admin --user=root

# kubectl get nodes
# kubectl get pods --all-namespaces
# kubectl get nodes