#! /bin/bash

# Control Plane Node(s)
sudo firewall-cmd --permanent --zone=public --add-port=6443/tcp # Kubernetes API server
sudo firewall-cmd --permanent --zone=public --add-port=2379-2380/tcp # etcd server client API
sudo firewall-cmd --permanent --zone=public --add-port=10250/tcp # Kubelet API
sudo firewall-cmd --permanent --zone=public --add-port=10251/tcp # kube-scheduler
sudo firewall-cmd --permanent --zone=public --add-port=10252/tcp # kube-controller-manager
sudo firewall-cmd --reload

# Enable the br_netfilter module for cluster communication
sudo modprobe br_netfilter
sudo echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
sudo echo '1' > /proc/sys/net/bridge/bridge-nf-call-ip6tables

sudo update-alternatives --set iptables /usr/sbin/iptables-legacy

sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

# Configure cgroup driver used by kubelet on control-plane node
sudo sed -i '/^KUBELET_EXTRA_ARGS=/ s/$/--cgroup-driver=systemd/' /etc/sysconfig/kubelet

# Ensure iptables aren't being bypassed
sudo cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

sudo systemctl enable --now kubelet

sudo mkdir /var/lib/weave
sudo echo "s3cr3tp4ssw0rd" > weave-passwd
sudo mv weave-passwd /var/lib/weave/

docker pull portainer/portainer
docker pull portainer/agent
docker pull storidge/cio
docker pull storidge/nfs

# kubectl get nodes
# kubectl get pods --all-namespaces
# kubectl get nodes