#! /bin/bash

firewall-cmd --permanent --zone=public --add-port=3260/tcp # ISCI
firewall-cmd --permanent --zone=public --add-port=8282/tcp # REST API
firewall-cmd --permanent --zone=public --add-port=8383/tcp # Secure cluster configuration
firewall-cmd --permanent --zone=public --add-port=16995/tcp # Metrics Exporter
firewall-cmd --permanent --zone=public --add-port=16996/tcp # DFS internode communications
firewall-cmd --permanent --zone=public --add-port=16997/tcp # SDS CLI server
firewall-cmd --permanent --zone=public --add-port=16998/tcp # Controller nodes hearbeat
firewall-cmd --permanent --zone=public --add-port=16999/tcp # DFS-CIO internode communication
firewall-cmd --permanent --zone=public --add-port=9000/tcp # Portainer
firewall-cmd --permanent --zone=public --add-port=6783/tcp # Weave Net
firewall-cmd --permanent --zone=public --add-port=6783-6784/udp # Weave Net
firewall-cmd --permanent --zone=public --add-port=8080/tcp
firewall-cmd --reload

yum remove -y vim-minimal
yum install -y vim-enhanced
yum install -y sudo

cat << EOF > ../.vimrc
syntax enable
colorscheme torte
EOF

chown sonny: ../.vimrc

cat << EOF > /root/.vimrc
syntax enable
colorscheme torte
EOF

yum install -y epel-release
yum install -y open-vm-tools-desktop wget mlocate elinks yum-utils net-tools autoconf bc bind-utils bison cryptsetup-luks expect gcc libyaml libyaml-devel lsof lsscsi iscsi-initiator-utils make net-tools pciutils subversion xfsprogs
yum install -y https://kojipkgs.fedoraproject.org//vol/fedora_koji_archive01/packages/fio/2.6/1.fc24/x86_64/fio-2.6-1.fc24.x86_64.rpm

yum update -y

yum clean all
rm -rf /var/cache/yum

# Add Kubernetes repo
sudo cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

sudo yum makecache -y

reboot