#! /bin/bash

yum remove -y vim-minimal
yum install -y vim-enhanced
yum install -y sudo

cat << EOF > ../.vimrc
syntax enable
colorscheme torte
EOF

chown sonny: ../.vimrc

cat << EOF > /root/.vimrc
syntax enable
colorscheme torte
EOF

yum install -y epel-release
yum install -y open-vm-tools-desktop wget mlocate elinks yum-utils net-tools
yum update -y

yum clean all
rm -rf /var/cache/yum
